"""add unique content hash to resumes

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 14:34:58.568963
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(
        'uq_resumes_content_hash',
        'resumes',
        ['content_hash'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_resumes_content_hash',
        'resumes',
        type_='unique',
    )
    op.drop_column('resumes', 'content_hash')
    # ### end Alembic commands ###
