"""add resume deletion state

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-09 12:21:38.704042
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('status', sa.Enum('ACTIVE', 'DELETING', 'DELETE_FAILED', name='resume_status', native_enum=False, create_constraint=True), server_default='ACTIVE', nullable=False))
    op.add_column('resumes', sa.Column('deletion_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('resumes', sa.Column('last_deletion_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'last_deletion_attempt_at')
    op.drop_column('resumes', 'deletion_attempts')
    op.drop_column('resumes', 'status')
    # ### end Alembic commands ###
